-- Tabela para guardar o histórico de conversas do WhatsApp
CREATE TABLE IF NOT EXISTS public.chat_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number text NOT NULL,
    role text NOT NULL CHECK (role IN ('user', 'assistant')),
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index para buscar histórico rapidamente pelo telefone
CREATE INDEX IF NOT EXISTS idx_chat_history_phone ON public.chat_history(phone_number);

-- RLS (Row Level Security) - Opcional se for acessar via API, mas bom ter
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;

-- Política: Permitir leitura/escrita pública (ajustar conforme necessidade de segurança)
-- Como o Bot usa chave de serviço/admin, ele ignora RLS, mas se o frontend for ler, precisa disso
CREATE POLICY "Enable read access for all users" ON "public"."chat_history"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all users" ON "public"."chat_history"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);
