-- Create the posts table
create table public.posts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  content text not null,
  topic text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For now, we allow public access for simplicity, but in production you should restrict this.
alter table public.posts enable row level security;

create policy "Enable read access for all users"
on public.posts for select
using (true);

create policy "Enable insert access for all users"
on public.posts for insert
with check (true);
